# Generated by Django 4.1.3 on 2022-11-08 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Название Фильма')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('year_of_execution', models.IntegerField(verbose_name='Год выпуска')),
                ('director', models.TextField(blank=True, verbose_name='Режиссер')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='films.films')),
            ],
        ),
        migrations.AddField(
            model_name='films',
            name='genre',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='films.genre'),
        ),
    ]
