# Generated by Django 4.1.3 on 2022-11-10 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_alter_films_options_films_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название зала')),
                ('capacity', models.IntegerField(default=50, verbose_name='Вместительность')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['id'], 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='sessions',
            options={'ordering': ['date'], 'verbose_name': 'Сеанс', 'verbose_name_plural': 'Сеансы'},
        ),
        migrations.AddField(
            model_name='films',
            name='country',
            field=models.CharField(default='America', max_length=150, verbose_name='Страна выпуска'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='films',
            name='genre',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='films.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='films',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='sessions',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='films.rooms'),
        ),
    ]
