# Generated by Django 4.1.3 on 2022-11-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_rooms_alter_genre_options_alter_sessions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='director',
            field=models.CharField(max_length=150, verbose_name='Режиссер'),
        ),
    ]
