# Generated by Django 4.1.3 on 2022-11-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_alter_films_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='photo',
            field=models.ImageField(null=True, upload_to='static/photos/%Y/%m/%d/'),
        ),
    ]
