# Generated by Django 4.1.3 on 2022-11-20 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_alter_films_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Подтвержденно'),
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='gallery/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='gallery/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='gallery/%Y/%m/%d/')),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='films.films')),
            ],
        ),
    ]
