# Generated by Django 4.1.3 on 2022-11-21 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_alter_films_is_published_photos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photos',
            options={'ordering': ['film'], 'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды'},
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='films.films')),
            ],
        ),
    ]
