# Generated by Django 4.1.3 on 2022-11-28 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0011_alter_photos_options_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='mainpage_photos/%Y/%m/%d/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['date_added'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='films.films', verbose_name='Фильм'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя пользователя'),
        ),
    ]
