# Generated by Django 4.1.3 on 2022-11-29 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_rename_photo_1_photos_photo_remove_photos_photo_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpagecarousel',
            options={'ordering': ['pk'], 'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды (Главная страница)'},
        ),
    ]
