# Generated by Django 4.1 on 2022-11-29 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0014_alter_mainpagecarousel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['date_added'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='films',
            options={'ordering': ['id'], 'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['id'], 'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='mainpagecarousel',
            options={'ordering': ['pk'], 'verbose_name': 'Slide', 'verbose_name_plural': 'Slides (Main page)'},
        ),
        migrations.AlterModelOptions(
            name='photos',
            options={'ordering': ['film'], 'verbose_name': 'Slide', 'verbose_name_plural': 'Slides(DetailView)'},
        ),
        migrations.AlterModelOptions(
            name='rooms',
            options={'ordering': ['id'], 'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterModelOptions(
            name='sessions',
            options={'ordering': ['date'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default='aka335814'),
        ),
        migrations.AlterField(
            model_name='films',
            name='country',
            field=models.CharField(max_length=150, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='films',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='films',
            name='director',
            field=models.CharField(max_length=150, verbose_name='Director'),
        ),
        migrations.AlterField(
            model_name='films',
            name='genre',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='films.genre', verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='films',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Confirmed'),
        ),
        migrations.AlterField(
            model_name='films',
            name='title',
            field=models.CharField(max_length=400, verbose_name='Movie name'),
        ),
        migrations.AlterField(
            model_name='films',
            name='year_of_execution',
            field=models.IntegerField(verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='capacity',
            field=models.IntegerField(default=50, verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Room'),
        ),
    ]
