# Generated by Django 4.1.3 on 2022-12-09 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0016_remove_films_genre_alter_genre_slug_films_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Username')),
                ('body', models.TextField(verbose_name='Comment')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0, max_length=5)),
                ('dislikes', models.IntegerField(default=0, max_length=5)),
            ],
        ),
        migrations.RenameModel(
            old_name='Sessions',
            new_name='Session',
        ),
        migrations.RenameModel(
            old_name='Films',
            new_name='Movie',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.AddField(
            model_name='vote',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='films.movie'),
        ),
        migrations.AddField(
            model_name='comment',
            name='film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='films.movie', verbose_name='Movie'),
        ),
    ]
