# Generated by Django 4.1.3 on 2022-12-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0017_comment_vote_rename_sessions_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, default='slug9789', max_length=400),
        ),
    ]
