# Generated by Django 4.1.3 on 2022-12-09 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0020_alter_movie_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['film'], 'verbose_name': 'Vote', 'verbose_name_plural': 'Votes'},
        ),
    ]
