# Generated by Django 4.1.3 on 2022-12-09 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0021_alter_vote_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='time',
            field=models.TimeField(default=datetime.time(0, 9, 54, 875732), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.date(2022, 12, 10), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='dislikes',
            field=models.IntegerField(default=0, verbose_name='Dislikes'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Likes'),
        ),
    ]
