# Generated by Django 4.1.3 on 2022-12-09 23:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0022_session_time_alter_session_date_alter_vote_dislikes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.TimeField(default=datetime.time(0, 46, 17, 869182), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='film',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='films.movie'),
        ),
    ]
