# Generated by Django 4.1.3 on 2022-12-10 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0023_alter_session_time_alter_vote_film'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['film'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.CharField(default='0', max_length=10, verbose_name='Rating'),
        ),
        migrations.AddField(
            model_name='movie',
            name='showtime',
            field=models.CharField(default='0', max_length=100, verbose_name='Showtime'),
        ),
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.TimeField(default=datetime.time(21, 54, 40, 634680), verbose_name='Time'),
        ),
    ]
