# Generated by Django 4.1.3 on 2022-12-10 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0024_alter_session_options_movie_rating_movie_showtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.URLField(blank=True, verbose_name='Trailer'),
        ),
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.TimeField(default=datetime.time(22, 47, 49, 473794), verbose_name='Time'),
        ),
    ]
