# Generated by Django 4.1.3 on 2022-12-10 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0025_movie_trailer_alter_session_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.TimeField(default=datetime.time(22, 55, 47, 999592), verbose_name='Time'),
        ),
    ]
